import os
import pydantic_settings

from typing import Optional

ENV_FILE = os.getenv("ENV_FILE", ".env")


class BaseSettings(pydantic_settings.BaseSettings):
    """Base class for loading settings.
    The setting variables are loaded from environment settings first, then from the defined env_file.

    Different groups/contexts of settings are created using different classes, that can define an env_prefix which
    will be concatenated to the start of the variable name."""
    class Config:
        env_file = ENV_FILE


class APISettings(BaseSettings):
    """Settings related with the FastAPI server"""
    host: str = "0.0.0.0"
    port: int = 5000

    class Config(BaseSettings.Config):
        env_prefix = "API_"


class APIDocsSettings(BaseSettings):
    """Settings related with the API autogenerated documentation"""
    title: str = "FastAPI Redis Idempotent API"
    """Title of the API"""
    description: Optional[str] = None
    """Description of the API"""
    version: str = "version"
    """Version of the API"""
    contact_name: Optional[str] = None
    """Name of the contact"""
    contact_email: Optional[str] = None
    """Email of the contact"""

    class Config(BaseSettings.Config):
        env_prefix = "API_DOCS_"


class RequestLoggingSettings(BaseSettings):
    """Settings related with the logging of requests"""
    level: str = "DEBUG"
    serialize: bool = False

    class Config(BaseSettings.Config):
        env_prefix = "REQUEST_LOG_"

class RedisSettings(BaseSettings):
    """Settings related with the Redis cache"""
    host: str = "localhost"
    port: int = 6379
    credentials_ssm_parameter: str = ""
    
    class Config(BaseSettings.Config):
        env_prefix = "REDIS_"


api_settings = APISettings()
api_docs_settings = APIDocsSettings()
request_logging_settings = RequestLoggingSettings()
redis_settings = RedisSettings()